<?
$PERM["lp(1)"]["8"]="X";
$PERM["lp"]["8"]="X";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["tools"]["2"]="D";
$PERM["tools"]["3"]="D";
$PERM["tools"]["4"]="D";
$PERM["tools"]["6"]="D";
$PERM["tools"]["5"]="D";
$PERM["tools"]["*"]="D";
$PERM["test.php"]["*"]="D";
$PERM["/"]["*"]="R";
?>